apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-simulator
  template:
    metadata:
      labels:
        app: iot-simulator
    spec:
      containers:
      - name: iot-simulator
        image: tousi/iot-simulator:v3

