apiVersion: v1
kind: Service
metadata:
  name: temperature-processor-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30010
  selector:
    app: temperature-processor

